version: '3.8'

services:
  familyhub:
    image: gutolm/familyhub:latest
    container_name: familyhub-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_PATH=/data/familyhub.db
      - JWT_SECRET=FamilyHubSecretKey_SuperSecure123! # Recomendado alterar para uma chave forte!
    volumes:
      - familyhub-data:/data

volumes:
  familyhub-data:
    driver: local
